aliases:
  - &restore-npm-cache
    restore_cache:
      name: Restore npm Package Cache
      keys:
        - npm-packages-{{ .Branch }}-{{ checksum "package-lock.json" }}

  - &save-npm-cache
    save_cache:
      name: Save npm Package Cache
      key: npm-packages-{{ .Branch }}-{{ checksum "package-lock.json" }}
      paths:
        - node_modules

  - &defaults
    docker:
      - image: circleci/node:lts-stretch

version: 2
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - *restore-npm-cache
      - run:
          name: "Install package root dependencies"
          command: "npm ci"
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
      - *save-npm-cache
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run build
      - store_artifacts:
          path: build
      - persist_to_workspace:
          root: .
          paths:
            - build
  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: "Run deploy script"
          command: "npm run deploy:ci -- --token=$FIREBASE_DEPLOY_TOKEN"

workflows:
  version: 2
  test-build-deploy:
    jobs:
      - install:
          filters:
            tags:
              only: /v(\d)+(\.(\d)+)+/
      - build:
          requires:
            - install
          filters:
            tags:
              only: /v(\d)+(\.(\d)+)+/
      - deploy:
          requires:
            - install
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v(\d)+(\.(\d)+)+/
